### ISSUE TITLE
Updates to information about surgeons

### ISSUE THREAD

**Issue by fallax** [genderkit/genderkit#100]
https://www.ngicns.scot.nhs.uk/nhsservices/adults/surgery/surgery-providers/

is a _really_ good list of UK surgery providers. It'd be really good if we could either link to this page, or incorporate information from it, somewhere.

It may be worth talking to NGICNS directly to find out if this information is likely to stay up-to-date and how complete it is, particularly if this is just surgeons that can be referred to from NHS Scotland or if it is a fairly complete list, so we can work out whether to copy and expand the data, or just link to it.

**Comment by jlphackett** [comment]
I sent them an e-mail today.

**Comment by jlphackett** [comment]
The list is updated quarterly, and includes all NHS surgeons in England.
