### ISSUE TITLE
Clearly label and separate UK-specific (and/or England/Wales/Scotland/NI-specific) information from the rest of the content

### ISSUE THREAD

**Issue by theshillito** [genderkit/genderkit#102]
Regarding https://github.com/orgs/genderkit/projects/1#card-28235648

There is information currently on the site that applies to certain parts of the UK and not others, but these aren't well labelled. I propose the following:

1) a page for each of the constituent parts of the UK with an overview of country-specific differences that are worth knowing as a resident there or perhaps when becoming a resident there

2) elsewhere on the site, a highlight of some kind (different colour background, border, etc) should be added to sections that only apply to specific part(s) of the UK. While initially, using emoji flags may seem appropriate, there isn't one for each part of the UK the site covers, and Northern Ireland only officially has 🇬🇧 which isn't ideal for plenty of other reasons. I'd therefore suggest a text label, maybe with a 🗺 or 🧭 as something generic.

**Comment by fallax** [comment]
Probably the most important page remaining that requires nation-specific advice is "name change by deed poll" (and probably also the stat dec page)

**Comment by fallax** [comment]
Something important worth highlighting with this - on the page listing all gender clinics, it would be important to highlight that which gender clinics you can be referred to depends on which UK nation you are in. For example, I think that in Scotland you are referred to the Scottish GIC that corresponds to the region of Scotland you live in, whereas in England you have free choice of any gender clinic, but we will need to check this.

**Comment by jlphackett** [comment]
Here's what I've managed to find out so far. I haven't looked into the youth situation in any of these places just yet.

In England:
- Adult patients can self-refer, but must be registered with a GP (nonsurgical service spec page 12)
- [This NHS England leaflet](https://www.nhs.uk/NHSEngland/patient-choice/Documents/patient-choice-leaflet.pdf) states that you have a right to choose where to be referred for any treatments, backed up by [this page](https://www.nhs.uk/using-the-nhs/about-the-nhs/your-choices-in-the-nhs/).

In Wales:
- Here is the [current service spec](http://www.whssc.wales.nhs.uk/sitesplus/documents/1119/CP182b%20Gender%20Identity%20Service%20for%20Adults%20%28non%20surgical%29%20Spec%20V2.0%20March%202020.pdf) and [policy](http://www.whssc.wales.nhs.uk/sitesplus/documents/1119/CP182a%5FGender%20Identity%20Service%20for%20Adults%20%28non%20surgical%29%20Policy%20V3.0%20March%202020.pdf) for non-surgical. They use England's spec for surgical services.
- NB the protocol we currently link to is under review, so might change. The two linked above are more recent and are not currently under review.
- CP182b p9. states that referrals must be made by GP to the Welsh service. "Complex cases" then get sent to England, as do surgical referrals.
- There's only one service in Wales. I would assume you get to choose which England clinic to get sent on to if they decide you're a complex case, but it's not totally clear.

In Scotland:
- Some clinics, [but not all](https://www.ngicns.scot.nhs.uk/gender-identity-clinics/), accept self-referral.
- [Sandyford](https://www.sandyford.scot/sexual-health-services/gender-identity-service/) will accept referrals (and self-referrals) from anywhere in Scotland, but the other clinics are limited to specific regions.

In NI:
- There is only one adult service in NI, and you cannot self-refer. (https://transgenderni.org.uk/healthcare/)
