### ISSUE TITLE
Add data about age restrictions to ID documents pages

### ISSUE THREAD

**Issue by fallax** [genderkit/genderkit#115]
We need to indicate the situation for younger people on pages about updating ID documents. Starting points for researching this information might be:

- http://genderedintelligence.co.uk/projects/kip/transitioning
- https://mermaidsuk.org.uk/young-people/resources-for-young-people/
- information on gov.uk is also often very helpful

Information about pages needs to be put in a consistent format into the files ```_data/articles/*.yaml``` so that it can be read out by the changes to implement issue #101

**Comment by elnicholls** [comment]
Pages updated with age info:
- Getting a new passport
- Name change by deed poll
- Telling organisations
- Registering a name change
