### ISSUE TITLE
Check site for any other articles describing things that might have additional conditions for younger people

### ISSUE THREAD

**Issue by fallax** [genderkit/genderkit#116]
Some activities described on the site might have additional restrictions or be off-limits for younger people - think for example, tattoos? piercings? It is important to check that all these have been caught, and information added to the pages to indicate this.

The complete list of "how to" articles are currently linked to from https://genderkit.org.uk/error/ so it would be easiest to work through this alphabetical list.

**Comment by fallax** [comment]
A good candidate for this is the Counselling page

**Comment by fallax** [comment]
There are a number of medicines we list which have manufacturers warnings against use or recommendations against use by children (and sometimes also women, pregnant, lactating, or possibly pregnant people):
- Finasteride https://www.nhs.uk/medicines/finasteride/
- Eflornithine https://www.medicines.org.uk/emc/files/pil.6398.pdf (already some warnings on https://genderkit.org.uk/article/eflornithine/)
- Cyproterone https://www.medicines.org.uk/emc/product/1120/smpc
- Spironolactone https://www.medicines.org.uk/emc/files/pil.5919.pdf
- Anastrozole https://www.medicines.org.uk/emc/product/2749/smpc
- and possibly others?
We should consider carefully how best to warn on these pages - ideally by linking to somewhere else for the information, rather than trying to give medical information that is outside of the core hormone meds stuff that we can put focused effort into maintaining.

**Comment by jlphackett** [comment]
- Permanent makeup is a tattooing, so min age 18
- Piercings require you to be 16 in Scotland; elsewhere individual piercing shops may have their own policies
- Erectile dysfunction meds generally require you to be 18

**Comment by jlphackett** [comment]
Razor blades are age restricted to 18+, but disposable razors aren't so long as no more than 2mm of the blade is exposed
