### ISSUE TITLE
Update help resources pages with information for young people

### ISSUE THREAD

**Issue by fallax** [genderkit/genderkit#118]
Currently these pages don't have specific information for younger people, and could potentially link to UK charities/organisations that provide helpful crisis services for younger people:

- https://genderkit.org.uk/resources/housing/
- https://genderkit.org.uk/resources/violence/
- https://genderkit.org.uk/resources/mental-health/
- https://genderkit.org.uk/resources/sex/

**Comment by jlphackett** [comment]
I added a link to AKT's guidance pages on the housing page; there's probably more that can be added there (including stuff for under 16s, which AKT don't cover), and I haven't added any youth-specific info to the other pages yet.

**Comment by jlphackett** [comment]
Maybe add a link to Childline to the violence page?
