### ISSUE TITLE
Add additional health warnings for younger people

### ISSUE THREAD

**Issue by fallax** [genderkit/genderkit#119]
For some articles, additional warnings need to be added. This if if doing the thing described in an article could potentially have negative health effects specifically to people who were growing or going through puberty.

Health warnings can be added into articles using the "warning" template, e.g. as in this example from https://genderkit.org.uk/article/binding/ :

```{% capture warn %} The health risks of binding are almost entirely unstudied and unknown, and are associated with a number of health problems. Research suggests you should take rest days where you do not bind as much as you can {% cite peitzmeier2017health %}. Do not use "home made" binders made from elastic bandages, duct tape and plastic wrap. {% endcapture %} {% include warning warning=warn %}```

**Comment by jlphackett** [comment]
Articles that might need extra health warnings:
- Binding
- Botox
- Corsets
- Voice surgeries and chest surgeries - might not be a health warning so much as a "probs best to wait until you've finished puberty" thing

**Comment by jlphackett** [comment]
Other articles it occurs to me might need such warnings:
- Dieting (people still developing should be careful not to eat too little)
- Cosmetic facial surgeries such as forehead recontouring, rhinoplasty
- Is there any info about there about tucking when you're still going through puberty?
