### ISSUE TITLE
GnRH agonists: puberty blocking detail

### ISSUE THREAD

**Issue by fallax** [genderkit/genderkit#121]
GnRH agonists page needs more detail about their use for puberty blocking; in particular, the safety of doing so and the potential advantages and disadvantages. Any statements in this area must have citations to research articles published in reputable journals, and worded as carefully as possible.

Useful research studies might be found:
- https://www.transactual.org.uk/research
- https://gids.nhs.uk/evidence-base

It might be also worth checking if there is anything useful in genderarchive:
- https://genderarchive.org.uk/tag/hormones/
- https://genderarchive.org.uk/tag/youth/

Where possible try not to duplicate information that is already available elsewhere - if you can say "there is more information about <x> on the <y> website" and link to that instead, do so, rather than us having to keep up-to-date information on a potentially controversial area.

**Comment by fallax** [comment]
See also https://www.tandfonline.com/doi/full/10.1080/14647273.2017.1422297

**Comment by jlphackett** [comment]
I think this is fixed as of d58eb0a65c61782ff6b9e57aa03e83f667dbe5ca and 112726cf54309e73eb21f075cfd8a20dc7b8a2a9? Happy to reopen if there's anything else we need to add, but otherwise I'm considering this closed.
