### ISSUE TITLE
Add NHS Grampian gender clinic

### ISSUE THREAD

**Issue by fallax** [genderkit/genderkit#136]
Currently we don't list the Grampian gender clinic.

We need to know:

- are they currently accepting referrals for new patients?
- what age will they accept referrals from?
- for a referral to be accepted to Grampian, where can you be registered with a GP? Is it still true that Orkney and Shetland patients can be referred?

As they don't currently have a website, we could link to the NGICNS gender clinics page, maybe? Or just not have a link at all?

**Comment by jlphackett** [comment]
Sent some e-mails asking these questions today.
