### ISSUE TITLE
New page: more contraception pages

### ISSUE THREAD

**Issue by jlphackett** [genderkit/genderkit#140]
We need to add pages about other contraception methods, such as barriers, IUDs and the like.

See Faculty of Sexual and Reproductive Healthcare advice: https://www.fsrh.org/standards-and-guidance/documents/fsrh-ceu-statement-contraceptive-choices-and-sexual-health-for/contraceptive-choices-and-sexual-health-for-transgender-non-binary-people-oct-2017.pdf

**Comment by fallax** [comment]
We should make sure this includes vasectomy and tubal ligation.
