### ISSUE TITLE
Make it clear that local MH/CAMHS do not need to be seen before gender clinic referral

### ISSUE THREAD

**Issue by fallax** [genderkit/genderkit#150]
As this has changed relatively recently in Wales we should probably make this explicitly stated on:

- the information for clinicians page
- the gender clinics page
- possibly the formal diagnosis page?

**Comment by jlphackett** [comment]
Resolved by f096e62e792d9aca902222a5beb0fa8c5587e8e0. Didn't add anything to the formal diagnosis page. I think the information is better on just the other two pages for now: fewer things to update.
