### ISSUE TITLE
Automatically increment CSS query string number somehow, or remove it entirely

### ISSUE THREAD

**Issue by fallax** [genderkit/genderkit#156]
We've currently got a bit of a nasty hack for ensuring that cached CSS doesn't cause problems during a major site upgrade.

It's easy to forget to update this each time we do a big upgrade though, so we need a way to make sure that can't cause issues.

**Comment by jlphackett** [comment]
In deploy script, make a random number and pipe that into Jekyll as a parameter. Build script can send in a fixed number.
