### ISSUE TITLE
Update information for EU citizens and immigrants to the UK post-Brexit

### ISSUE THREAD

**Issue by fallax** [genderkit/genderkit#195]

**Comment by fallax** [comment]
This will mostly be information on the page https://genderkit.org.uk/resources/immigration/ but may also affect the includes relating to costs and funding.

**Comment by jlphackett** [comment]
oops why did I think this was 131 https://github.com/genderkit/genderkit/commit/29c326e71ffd5b8311fd6d19f8035a6a58390d5e
