### ISSUE TITLE
Passport updates: clarify situation for people with dual citizenship

### ISSUE THREAD

**Issue by fallax** [genderkit/genderkit#196]
My understanding is that the UK guidance is you're supposed to update the non-UK passport first, unless it's a situation where you cannot. We need to check this

**Comment by WriterToad** [comment]
Sources:

HMPO information document: [https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/251703/Applying_for_a_passport_additional_information.PDF](Here.)

Home Office change of names guidance: [https://www.gov.uk/government/publications/change-of-name-guidance/use-and-change-of-names#exceptions-guidance](Here - note there's an exception for those who can't change their other passport.)

**Comment by WriterToad** [comment]
Fixed in pull request, closed.
