### ISSUE TITLE
Add packer companies

### ISSUE THREAD

**Issue by WriterToad** [genderkit/genderkit#217]
We need a list of well-known packer companies outside of the UK

**Comment by fallax** [comment]
We should also add https://uktransshop.co.uk/ who do packing pouches

**Comment by fallax** [comment]
We should also update the "how much does it cost" information, as this isn't correct any more, and highlight that some packers and accessories can be bought for very little money

**Comment by fallax** [comment]
Added some of this information in f09ce4f. Need to work out what criteria we are using for whether we add a manufacturer / retailer or not if they are outside of the UK.
