### ISSUE TITLE
Update information on surgery costs

### ISSUE THREAD

**Issue by fallax** [genderkit/genderkit#22]
Currently a number of articles are marked "TODO" for costs.

These are all surgical procedures.

This will require the website to be live (so that how the information will be used can be demonstrated) and phoning or emailing surgical teams to find this information out.

**Comment by fallax** [comment]
This also applies to the electrolysis article. Finding out the information about electrolysis may be more difficult - may need to locate an technician who specialises in trans clients. There may still be one working with Transhealth?

**Comment by fallax** [comment]
Sadly the surgery teams didn't get back to me about pricing.

The private pricing sections have been removed from the pages for the moment.

**Comment by Kikami** [comment]
With regards to electrolysis and technicians who specialise in trans clients, there are specific codes provided by the BIAE that a technician can apply to their professional profile to make them easy to find. Specifically, there is TG (Beard removal for Trans clients), and SRS (preSRS hair removal). This can be found here:
https://electrolysis.co.uk/member-directory/

Regarding costs, it could be worth mentioning the total cost cap the NHS places on facial hair removal (£1600)?

**Comment by fallax** [comment]
Cost information we already list:

- phalloplasty
- metoidioplasty
- vaginoplasty
- electrolysis

Costs that we should definitely add:

- mastectomy
- orchidectomy
- laser hair removal

Also potentially important:

- hysterectomy
