### ISSUE TITLE
Add information about what to expect in appointments

### ISSUE THREAD

**Issue by fallax** [genderkit/genderkit#225]
This could include:

- what to expect when you initially go to your GP to ask for a referral
- what to expect when you have your initial GIC/private clinic appointment
- what to expect in a surgical consultation

**Comment by fallax** [comment]
Some initial starting points:

- The information in the post here (Dr Coxon, private): https://old.reddit.com/r/transgenderUK/comments/bh9i9i/gendercare_medical_appointment/
- The information in the post here (WGS): https://www.reddit.com/r/transgenderUK/comments/o7s5ca/first_appointment_with_welsh_gender_services_what/
- the following list provided by a volunteer from a Dr Lorimer appointment: "when did you start feeling like something was wrong / did you try to present in [x] way during childhood via clothes, makeup, etc? / Are your family, work and social circle both aware and supportive? / what changes do you seek from treatment? / what's your sexual orientation? / Have you had physical relationships? / [...] genital dysphoria stuff / are you aware that getting genital surgery is irreversible?"

We may also want to signpost to this information about how to prepare for an appointment:

- https://old.reddit.com/r/transgenderUK/comments/d6uju9/deleted_by_user/

**Comment by fallax** [comment]
Started a google doc for this containing ideas

**Comment by fallax** [comment]
Draft versions added for what to expect when requesting a referral and what to expect in an initial assessment appointment

**Comment by fallax** [comment]
Closing this defect as we've got the two most important bits of it done and checked in. What to expect in a surgical consultation is much less of a priority, creating a separate issue for that.

**Comment by jlphackett** [comment]
Delaying surgical consult stuff to #277
