### ISSUE TITLE
New article: Bras

### ISSUE THREAD

**Issue by jlphackett** [genderkit/genderkit#241]
Something talking about all the different types of bra and how they might be able to increase or decrease apparent bust size? Probably goes in both "Clothing" and "Upper body" sections.

**Comment by fallax** [comment]
e.g. padding, push-up bras, sports bras, bras with pockets for inserts, mastectomy bras, etc.

**Comment by jlphackett** [comment]
notes from discussion:
can get measuring tape in pound shops or wilko
Or supermarkets
Is this 'too large a bra can look unnatural' bit necessary - it seems a bit prescriptive for us
more about making sure the weight of what you are wearing is natural if you're using padding or whatever
bras and sensory problems
And making it clear you can get ones that are not lacy
I think also there are things you can use on the straps, and things you can use on the hooks bit also
