### ISSUE TITLE
Surgery pages - include GDNRSS level 2 helpline details

### ISSUE THREAD

**Issue by fallax** [genderkit/genderkit#255]
This new service is able to answer many medical questions about surgery. We should expand the existing include to include info about this. We have a leaflet with details about this that we may want to link to and which provides info about what kind of questions they can answer.

**Comment by jlphackett** [comment]
Got a link to the leaflet?

**Comment by fallax** [comment]
@jlphackett at the moment we only have a PDF that has been emailed to us. Should be in your genderkit email account.

**Comment by fallax** [comment]
We'll have to host the leaflet ourselves in the assets folder, for now, unless we can think of a better location for it.

**Comment by jlphackett** [comment]
feels like a genderarchive thing maybe?
