### ISSUE TITLE
Deed polls: add list of suggestions of witnesses

### ISSUE THREAD

**Issue by fallax** [genderkit/genderkit#473]

**Comment by WriterToad** [comment]
Do we not have this already?

"You will need to obtain the signatures of two independent witnesses to your deed poll. These need to be people who know you personally but who are not part of your family. Some people who might be able to help you with this are neighbours, friends, coworkers, lecturers, or youth club leaders."

**Comment by fallax** [comment]
Fixed by commit 50e1831
