### ISSUE TITLE
Update status of the Gender Recognition Reform (Scotland) Bill

### ISSUE THREAD

**Issue by gsnedders** [genderkit/genderkit#475]
https://genderkit.org.uk/article/obtaining-a-grc/ says:

> Due to the recent passage of the Gender Recognition Reform (Scotland) Bill, processes relating to obtaining a GRC may change in Scotland in the near future.

This, of course, did not come to be, and the Scottish Government lost their request for judicial review.

Shirley-Anne Somerville MSP, on behalf of the Scottish Government, did say:

> For the avoidance of doubt, this bill is not in the bin and is waiting an incoming UK government that has more respect for devolution.

So while potentially the UK Government _could_ amend the secondary legislation (i.e., the Section 35 order), especially following a change of, uh, government, this is primarily a hypothetical concern until such time that there is any attempt to make such legislation. (And being secondary legislation, this will likely happen quite quickly!)

**Comment by fallax** [comment]
Thanks - have updated this to remove this notice and should be up in the next version (probably live in the next few days)
