### ISSUE TITLE
Dead link - NHS Scotland NHS PDF about electrolysis timeframes

### ISSUE THREAD

**Issue by SleepyCatten** [genderkit/genderkit#485]
**Affected page:** https://genderkit.org.uk/article/electrolysis/#ngicns2020facial

**Dead link:** https://www.ngicns.scot.nhs.uk/wp-content/uploads/2020/04/Facial-Hair-Removal-Guidelines-for-NHS-Boards-re.-Transgender-Patients-v1.0.pdf

**Updated link:** https://www.nn.nhs.scot/ngicns/wp-content/uploads/sites/17/2022/08/2022-Facial-Hair-Removal-Guidelines-for-NHS-Boards-re.-Transgender-Patients-v1.0.pdf

**Additional:** It's on page 9 of the new document, rather than page 6.

**Comment by fallax** [comment]
Thank you, this was actually broken on five different pages - should be fixed in the next version
