### ISSUE TITLE
Updating / adding NHS England PCSE link

### ISSUE THREAD

**Issue by SleepyCatten** [genderkit/genderkit#487]
Hi there

**Affected page:** https://genderkit.org.uk/article/updating-nhs-patient-details/

**Affected text / link:** "on the PCSE website" -- currently links to https://pcse.england.nhs.uk/help/registrations/adoption-and-gender-re-assignment-processes/ but this is more for GP enquiries - the processes are listed here - https://pcse.england.nhs.uk/help/patient-registrations/adoption-and-gender-reassignment-processes

**Suggested change:** either simply update the link or amend the section to include both links

e.g., ... on the PCSE website on the [adoption and gender reassignment processes page](https://pcse.england.nhs.uk/help/patient-registrations/adoption-and-gender-reassignment-processes). If the GP surgery has any queries that are not answered here, they can contact the PCSE with queries about adoptions and gender reassignments [via this page](https://pcse.england.nhs.uk/contact-us/patient-registrations-enquiry-categories/adoptions-and-gender-reassignment).

**Comment by fallax** [comment]
Fixed, should be live on the site in the next week or so - will be running a big site update soon. Thank you for reporting this - much appreciated!
