### ISSUE TITLE
New publications to add

### ISSUE THREAD

**Issue by fallax** [genderkit/genderkit#74]
- http://www.elmmb.nhs.uk/_resources/assets/attachment/full/0/17370.pdf
- https://shsc.nhs.uk/wp-content/uploads/2016/04/SSC1620_GD-Prescribing.pdf
- https://gendergp.co.uk/wp-content/uploads/2018/02/GMC-advice-to-GPs-on-online-specialists.pdf

**Comment by fallax** [comment]
- http://www.rcpsych.ac.uk/pdf/PS02_18.pdf

**Comment by Kikami** [comment]
There is a trans screening services document available that would be additional to the two already listed on "Updating NHS patient details"

- https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/623309/Transgender_cross_programme_screening_leaflet.pdf

**Comment by fallax** [comment]
UK Visas and Immigration https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/257387/genderissueintheasylum.pdf
