### ISSUE TITLE
Proofreading

### ISSUE THREAD

**Issue by Kikami** [genderkit/genderkit#76]
http://genderkit.org.uk/article/getting-a-new-passport/
- "anytime" -> "any time"
- "up update" -> "update"
- "the document they do" -> "the document. They do" OR "the document; they do"
- "general practitioner" -> "GP" (not incorrect, just for simplicity and brevity)

"If you do not have a passport or a GRC and updated birth certificate:

You will need to fill in the application for a new passport and include your birth or adoption certificate along with the documents listed above."

I think the new line should be removed from between these two sentences, as when skimreading they look like unrelated paragraphs. Same goes for the set of sentences below these also.

**Comment by Kikami** [comment]
http://genderkit.org.uk/article/name-change-by-deed-poll/
"witnessed a solicitor" -> "witnessed **by** a solicitor"

**Comment by fallax** [comment]
Wondering if we might want to rerun [Proselint](http://proselint.com/) on the site which should find some more problems like this automatically

**Comment by Kikami** [comment]
http://genderkit.org.uk/article/telling-organisations/
Inconsistency when linking to GOV.UK; some entries have the link as "the GOV.UK website" (i.e. including the "the"), and some are just "GOV.UK website (not including the "the").
