### ISSUE TITLE
"Titles" page: no link to information about how to change them!

### ISSUE THREAD

**Issue by fallax** [genderkit/genderkit#99]
We should link to the Name Change by Deed Poll, Name Change by Statutory Declaration, and Telling Organisations pages, I think?

**Comment by theshillito** [comment]
I agree with linking to the pages, as long as it's made clear that there's no legal requirement to get a deed poll for changing titles, and there's similarly no requirement to be consistent with them (especially if your title of choice is not available).

**Comment by fallax** [comment]
Fixed by https://github.com/genderkit/genderkit/commit/bc31460e67fb020e88379c71d6e436a892561e40
